2025-03-26 18:19:45 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 18:21:21 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 18:21:43 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 18:44:58 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 18:45:24 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 19:48:29 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 19:48:47 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C957C52A50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')': /session/4603ade808e79f2073ac3b8f25a1824c/element
2025-03-26 19:48:51 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C957CA96D0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')': /session/4603ade808e79f2073ac3b8f25a1824c/element
2025-03-26 19:48:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C957CA9590>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')': /session/4603ade808e79f2073ac3b8f25a1824c/element
2025-03-26 19:51:09 - ERROR - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 533, in salir
    def salir(icon, item):
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 528, in detener
    icon.icon = crear_icono_rojo()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-03-26 19:51:13 - ERROR - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 533, in salir
    def salir(icon, item):
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 528, in detener
    icon.icon = crear_icono_rojo()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-03-26 19:51:36 - ERROR - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 535, in salir
    detener(icon, item)
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 530, in detener
    print("Script detenido.")
    ~~~~~^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-03-26 19:52:13 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 19:53:33 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 19:53:49 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000173305D2A50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')': /session/76a3820f920c172569d7424e74ecdb07/element
2025-03-26 19:53:53 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017330628F50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')': /session/76a3820f920c172569d7424e74ecdb07/element
2025-03-26 19:53:57 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000173306296D0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión')': /session/76a3820f920c172569d7424e74ecdb07/element
2025-03-26 19:54:01 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 19:54:11 - ERROR - An error occurred when calling message handler
Traceback (most recent call last):
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        uMsg, lambda w, l: 0)(wParam, lParam) or 0)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
    ~~~~~~~~^^^^^^
  File "C:\Users\migue\AppData\Local\Programs\Python\Python313\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 535, in salir
    detener(icon, item)
    ~~~~~~~^^^^^^^^^^^^
  File "C:\Users\migue\Desktop\pyAlhambra\pyAlhambra\pyAlhambraNotifications.py", line 530, in detener
    print("Script detenido.")
    ~~~~~^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
2025-03-26 20:00:18 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:11:15 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:12:08 - INFO - Días tachados inicialmente: ['26', '27', '28', '29', '31', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
2025-03-26 20:12:08 - INFO - 
 Intento #1
2025-03-26 20:12:24 - INFO - Días tachados actuales: ['26', '27', '28', '29', '31', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
2025-03-26 20:13:26 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:14:09 - INFO - Días tachados inicialmente: ['26', '27', '28', '29', '30', '31', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
2025-03-26 20:14:09 - INFO - 
 Intento #1
2025-03-26 20:14:23 - INFO - Días tachados actuales: ['26', '27', '28', '29', '30', '31', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
2025-03-26 20:16:38 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:17:13 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:18:01 - INFO - Días tachados inicialmente: ['26', '27', '28', '29', '30', '31', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
2025-03-26 20:18:01 - INFO - 
 Intento #1
2025-03-26 20:18:17 - INFO - Días tachados actuales: ['26', '27', '28', '29', '30', '31', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
2025-03-26 20:24:29 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:25:17 - INFO - Días tachados inicialmente: ['March-26', 'March-27', 'March-28', 'March-29', 'March-30', 'March-31', 'April-1', 'April-2', 'April-3', 'April-4', 'April-5', 'April-6', 'April-7', 'April-8', 'April-9', 'April-10', 'April-11', 'April-12', 'April-13', 'April-14', 'April-15', 'April-16', 'April-17', 'April-18', 'April-19', 'April-20', 'April-21', 'April-22', 'April-23', 'April-24', 'April-25', 'April-26', 'April-27', 'April-28', 'April-29', 'April-30']
2025-03-26 20:25:17 - INFO - 
 Intento #1
2025-03-26 20:25:31 - INFO - Días tachados actuales: ['March-26', 'March-27', 'March-28', 'March-29', 'March-30', 'March-31', 'April-1', 'April-2', 'April-3', 'April-4', 'April-5', 'April-6', 'April-7', 'April-8', 'April-9', 'April-10', 'April-11', 'April-12', 'April-13', 'April-14', 'April-15', 'April-16', 'April-17', 'April-18', 'April-19', 'April-20', 'April-21', 'April-22', 'April-23', 'April-24', 'April-25', 'April-26', 'April-27', 'April-28', 'April-29', 'April-30']
2025-03-26 20:26:38 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:27:12 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:28:09 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:28:47 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:30:32 - INFO - patching driver executable C:\Users\migue\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2025-03-26 20:31:28 - INFO - Días tachados inicialmente: ['March-26', 'March-27', 'March-28', 'March-29', 'March-30', 'March-31', 'April-1', 'April-2', 'April-3', 'April-4', 'April-5', 'April-6', 'April-7', 'April-8', 'April-9', 'April-10', 'April-11', 'April-12', 'April-13', 'April-14', 'April-15', 'April-16', 'April-17', 'April-18', 'April-19', 'April-20', 'April-21', 'April-22', 'April-23', 'April-24', 'April-25', 'April-26', 'April-27', 'April-28', 'April-29', 'April-30']
2025-03-26 20:31:28 - INFO - 
 Intento #1
2025-03-26 20:31:40 - INFO - Días tachados actuales: ['March-26', 'March-27', 'March-28', 'March-29', 'March-30', 'March-31', 'April-1', 'April-2', 'April-3', 'April-4', 'April-5', 'April-6', 'April-7', 'April-8', 'April-9', 'April-10', 'April-11', 'April-12', 'April-13', 'April-14', 'April-15', 'April-16', 'April-17', 'April-18', 'April-19', 'April-20', 'April-21', 'April-22', 'April-23', 'April-24', 'April-25', 'April-26', 'April-27', 'April-28', 'April-29', 'April-30']
2025-03-26 20:32:12 - INFO - 
 Intento #2
2025-03-26 20:32:25 - INFO - Días tachados actuales: ['March-26', 'March-27', 'March-28', 'March-29', 'March-30', 'March-31', 'April-1', 'April-2', 'April-3', 'April-4', 'April-5', 'April-6', 'April-7', 'April-8', 'April-9', 'April-10', 'April-11', 'April-12', 'April-13', 'April-14', 'April-15', 'April-16', 'April-17', 'April-18', 'April-19', 'April-20', 'April-21', 'April-22', 'April-23', 'April-24', 'April-25', 'April-26', 'April-27', 'April-28', 'April-29', 'April-30']
