2025-03-26 19:36:22 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "selenium\webdriver\common\service.py", line 176, in _terminate_process
  File "subprocess.py", line 1683, in terminate
OSError: [WinError 6] Controlador no válido
